# Uncomment if you want to use docker-in-docker
# image: gsiupm/dockermake:latest
# services:
# - docker:dind
# When using dind, it's wise to use the overlayfs driver for
# improved performance.

stages:
  - test
  - push
  - deploy
  - clean

before_script:
  - make -e login

.test: &test_definition
  stage: test
  script:
    - make -e test-$PYTHON_VERSION

test-2.7:
  <<: *test_definition
  variables:
    PYTHON_VERSION: "2.7"

test-3.5:
  <<: *test_definition
  variables:
    PYTHON_VERSION: "3.5"

.image: &image_definition
  stage: push
  script:
    - make -e push-$PYTHON_VERSION
  only:
    - tags
    - triggers

push-2.7:
  <<: *image_definition
  variables:
    PYTHON_VERSION: "2.7"

push-latest:
  <<: *image_definition
  variables:
    PYTHON_VERSION: latest
  only:
    - master
    - triggers

deploy:
  stage: deploy
  environment: production
  script:
    - make -e deploy
  only:
    - master

clean :
  stage: clean
  script:
    - make -e clean
  when: manual

cleanup_py:
   stage: clean
   when: always   # this is important; run even if preceding stages failed.
   script:
    - docker logout
